import {
  ACCOUNT_TYPE_OPTIONS,
  ACCOUNT_HEALTH_OPTIONS,
  OPPORTUNITY_STAGE_OPTIONS,
  OPPORTUNITY_TYPE_OPTIONS,
  SERVICE_LINE_OPTIONS,
  OPPORTUNITY_HEALTH_OPTIONS,
  ACTION_ITEM_STATUS_OPTIONS,
  ACTION_ITEM_TYPE_OPTIONS,
  AOP_YEAR_OPTIONS,
  DEFAULT_AOP_YEAR,
  TOWER_OPTIONS,
  DELIVERY_MODEL_OPTIONS,
  BILLING_MODEL_OPTIONS,
  PRIORITY_OPTIONS,
  INDUSTRY_OPTIONS,
} from '@/constants';
import type { IEModuleKey, ModuleIEConfig, RefData } from './types';

const PRIORITY = ['High', 'Medium', 'Low'] as const;
const INFLUENCE = ['High', 'Medium', 'Low'] as const;
const RELATIONSHIP = ['Strong', 'Neutral', 'Weak'] as const;

const accName = (id: string, ref: RefData) => ref.accounts.find((a) => a.id === id)?.name ?? '';
const oppName = (id: string, ref: RefData) => ref.opportunities.find((o) => o.id === id)?.name ?? '';

// ─── Accounts ─────────────────────────────────────────────────────────────────
const accountsConfig: ModuleIEConfig = {
  moduleKey: 'accounts',
  label: 'Accounts',
  singular: 'Account',
  duplicateKeyLabel: 'Account Name (case-insensitive)',
  fields: [
    { key: 'name', header: 'Account Name', headerAliases: ['Target Corporate Account', 'Account'], type: 'string', required: true, example: 'Acme Corporation' },
    { key: 'type', header: 'Account Type', type: 'enum', options: ACCOUNT_TYPE_OPTIONS, required: true, example: 'Strategic' },
    { key: 'health', header: 'Health', type: 'enum', options: ACCOUNT_HEALTH_OPTIONS, required: true, example: 'Green' },
    { key: 'healthReason', header: 'Reason for Health', type: 'string', example: 'Strong account relationships' },
    { key: 'industry', header: 'Industry', type: 'enum', options: INDUSTRY_OPTIONS, default: 'Others', example: 'BFSI' },
    { key: 'revenue', header: 'Revenue', type: 'number', default: 0, example: '0', hint: 'Auto-calculated from opportunities; leave as 0' },
    { key: 'location', header: 'Location', type: 'string', example: 'United States' },
    { key: 'since', header: 'Customer Since', type: 'string', example: '2021' },
    { key: 'website', header: 'Website', type: 'string', format: 'website', example: 'www.acme.com' },
    { key: 'phone', header: 'Phone', type: 'string', format: 'phone', example: '+1 555 0100' },
    { key: 'email', header: 'Email', type: 'string', format: 'email', example: 'contact@acme.com' },
    { key: 'address', header: 'Address', type: 'string' },
    { key: 'description', header: 'Description', type: 'string' },
    { key: 'tower', header: 'Tower', type: 'enum', options: TOWER_OPTIONS, example: 'Tower 1' },
    { key: 'accountManagerId', header: 'Account Manager', type: 'reference', reference: 'user', example: 'John Manager' },
    { key: 'practiceLeadId', header: 'Practice Lead', type: 'reference', reference: 'user', example: 'Jane Lead' },
    { key: 'clientPartnerId', header: 'Client Partner', type: 'reference', reference: 'user', example: 'Robert Partner' },
    { key: 'verticalHeadId', header: 'Vertical Head', type: 'reference', reference: 'user', example: 'Alice Head' },
  ],
  exportColumns: [
    { key: 'name', header: 'Account Name', value: (e) => e.name ?? '' },
    { key: 'type', header: 'Account Type', value: (e) => e.type ?? '' },
    { key: 'health', header: 'Health', value: (e) => e.health ?? '' },
    { key: 'healthReason', header: 'Reason for Health', value: (e) => e.healthReason ?? '' },
    { key: 'industry', header: 'Industry', value: (e) => e.industry ?? '' },
    { key: 'owner', header: 'Owner', value: (e) => e.ownerName ?? e.owner ?? '' },
    { key: 'accountManagerId', header: 'Account Manager', value: (e) => e.accountManagerName ?? e.accountManagerId ?? '' },
    { key: 'practiceLeadId', header: 'Practice Lead', value: (e) => e.practiceLeadName ?? e.practiceLeadId ?? '' },
    { key: 'clientPartnerId', header: 'Client Partner', value: (e) => e.clientPartnerName ?? e.clientPartnerId ?? '' },
    { key: 'verticalHeadId', header: 'Vertical Head', value: (e) => e.verticalHeadName ?? e.verticalHeadId ?? '' },
    { key: 'status', header: 'Status', value: (e) => e.status ?? 'Active' },
    { key: 'revenue', header: 'Revenue', value: (e) => e.revenue ?? 0 },
    { key: 'location', header: 'Location', value: (e) => e.location ?? '' },
    { key: 'since', header: 'Customer Since', value: (e) => e.since ?? '' },
    { key: 'website', header: 'Website', value: (e) => e.website ?? '' },
    { key: 'phone', header: 'Phone', value: (e) => e.phone ?? '' },
    { key: 'email', header: 'Email', value: (e) => e.email ?? '' },
    { key: 'address', header: 'Address', value: (e) => e.address ?? '' },
    { key: 'description', header: 'Description', value: (e) => e.description ?? '' },
    { key: 'tower', header: 'Tower', value: (e) => e.tower ?? '' },
  ],
};

// ─── Opportunities ──────────────────────────────────────────────────────────
const opportunitiesConfig: ModuleIEConfig = {
  moduleKey: 'opportunities',
  label: 'Opportunities',
  singular: 'Opportunity',
  duplicateKeyLabel: 'Opportunity Name + Account',
  fields: [
    { key: 'name', header: 'Opportunity Name', type: 'string', required: true, example: 'Acme Platform Upgrade' },
    { key: 'accountId', header: 'Account', headerAliases: ['Target Corporate Account', 'Account Name'], type: 'reference', reference: 'account', required: true, example: 'Acme Corporation', hint: 'Must match an account in the Accounts sheet or an existing account' },
    { key: 'stage', header: 'Stage', type: 'enum', options: OPPORTUNITY_STAGE_OPTIONS, default: 'Lead', example: 'Qualified' },
    { key: 'value', header: 'Deal Value', type: 'number', default: 0, example: '50000' },
    { key: 'probability', header: 'Probability (%)', type: 'integer', example: '25', hint: '0–100' },
    { key: 'crmValue', header: 'Forecast Value', type: 'number', default: 0, example: '45000' },
    { key: 'opportunityType', header: 'Category', type: 'enum', options: OPPORTUNITY_TYPE_OPTIONS, required: true, example: 'Growth' },
    { key: 'serviceLine', header: 'Service Line', type: 'enum', options: SERVICE_LINE_OPTIONS, required: true, example: 'Cloud' },
    { key: 'aopAvailable', header: 'AOP Available', type: 'boolean', default: false, example: 'No' },
    { key: 'aopYear', header: 'AOP Year', type: 'enum', options: AOP_YEAR_OPTIONS, example: DEFAULT_AOP_YEAR, hint: 'One of the predefined financial years; required when AOP Available is Yes' },
    { key: 'serviceProviderStakeholderId', header: 'Owner', headerAliases: ['Service Provider Stakeholder', 'Service Provider Owner', 'Owner Stakeholder'], type: 'reference', reference: 'user', example: 'John Smith' },
    { key: 'allocationStartDate', header: 'Expected Project Start Date', headerAliases: ['Allocation Start Date', 'Project Start Date'], type: 'date', example: '2026-01-15' },
    { key: 'allocationEndDate', header: 'Expected Project End Date (Optional)', headerAliases: ['Allocation End Date', 'Expected Project End Date', 'Project End Date'], type: 'date' },
    { key: 'dealStartDate', header: 'Deal Start Date', type: 'date' },
    { key: 'dealCloseDate', header: 'Deal Close Date', type: 'date' },
    { key: 'nextStep', header: 'Next Step', type: 'string' },
    { key: 'risksAndDependencies', header: 'Risks & Dependencies', type: 'string' },
    { key: 'description', header: 'Description', type: 'string' },
    { key: 'opportunityHealth', header: 'Opportunity Health', type: 'enum', options: OPPORTUNITY_HEALTH_OPTIONS, example: 'Green' },
    { key: 'location', header: 'Location', type: 'string', example: 'United States' },
    { key: 'cost', header: 'Cost', type: 'number', example: '30000' },
    { key: 'grossMargin', header: 'Gross Margin (%)', type: 'number', example: '25.5', hint: '0–100, decimals allowed' },
    { key: 'priority', header: 'Priority', type: 'enum', options: PRIORITY_OPTIONS, example: 'High' },
    { key: 'deliveryModel', header: 'Delivery Model', type: 'enum', options: DELIVERY_MODEL_OPTIONS, example: 'Fixed Bid' },
    { key: 'billingModel', header: 'Billing Model', type: 'enum', options: BILLING_MODEL_OPTIONS, example: 'T&M' },
    { key: 'tower', header: 'Tower', type: 'enum', options: TOWER_OPTIONS, example: 'Tower 1' },
  ],
  exportColumns: [
    { key: 'name', header: 'Opportunity Name', value: (e) => e.name ?? '' },
    { key: 'accountId', header: 'Account', value: (e, ref) => e.accountName ?? accName(e.accountId, ref) },
    { key: 'stage', header: 'Stage', value: (e) => e.stage ?? '' },
    { key: 'value', header: 'Deal Value', value: (e) => e.value ?? 0 },
    { key: 'probability', header: 'Probability (%)', value: (e) => e.probability ?? 0 },
    { key: 'crmValue', header: 'Forecast Value', value: (e) => e.crmValue ?? 0 },
    { key: 'opportunityType', header: 'Category', value: (e) => e.opportunityType ?? '' },
    { key: 'serviceLine', header: 'Service Line', value: (e) => e.serviceLine ?? '' },
    { key: 'aopAvailable', header: 'AOP Available', value: (e) => (e.aopAvailable ? 'Yes' : 'No') },
    { key: 'aopYear', header: 'AOP Year', value: (e) => e.aopYear ?? '' },
    { key: 'serviceProviderStakeholderId', header: 'Owner', value: (e) => e.serviceProviderStakeholderName ?? e.serviceProviderStakeholder ?? e.ownerName ?? e.owner ?? '' },
    { key: 'allocationStartDate', header: 'Expected Project Start Date', value: (e) => e.allocationStartDate ?? '' },
    { key: 'allocationEndDate', header: 'Expected Project End Date (Optional)', value: (e) => e.allocationEndDate ?? '' },
    { key: 'dealStartDate', header: 'Deal Start Date', value: (e) => e.dealStartDate ?? '' },
    { key: 'dealCloseDate', header: 'Deal Close Date', value: (e) => e.dealCloseDate ?? '' },
    { key: 'financialYear', header: 'Financial Year', value: (e) => e.financialYear ?? '' },
    { key: 'quarter', header: 'Quarter', value: (e) => e.quarter ?? '' },
    { key: 'nextStep', header: 'Next Step', value: (e) => e.nextStep ?? '' },
    { key: 'risksAndDependencies', header: 'Risks & Dependencies', value: (e) => e.risksAndDependencies ?? '' },
    { key: 'description', header: 'Description', value: (e) => e.description ?? '' },
    { key: 'opportunityHealth', header: 'Opportunity Health', value: (e) => e.opportunityHealth ?? '' },
    { key: 'location', header: 'Location', value: (e) => e.location ?? '' },
    { key: 'cost', header: 'Cost', value: (e) => e.cost ?? 0 },
    { key: 'grossMargin', header: 'Gross Margin (%)', value: (e) => e.grossMargin ?? '' },
    { key: 'priority', header: 'Priority', value: (e) => e.priority ?? '' },
    { key: 'deliveryModel', header: 'Delivery Model', value: (e) => e.deliveryModel ?? '' },
    { key: 'billingModel', header: 'Billing Model', value: (e) => e.billingModel ?? '' },
    { key: 'tower', header: 'Tower', value: (e) => e.tower ?? '' },
  ],
};

// ─── Stakeholders ─────────────────────────────────────────────────────────────
const stakeholdersConfig: ModuleIEConfig = {
  moduleKey: 'stakeholders',
  label: 'Stakeholders',
  singular: 'Stakeholder',
  duplicateKeyLabel: 'Email + Account',
  fields: [
    { key: 'name', header: 'Name', type: 'string', required: true, example: 'Jane Doe' },
    { key: 'accountId', header: 'Account', headerAliases: ['Account Name'], type: 'reference', reference: 'account', required: true, example: 'Acme Corporation', hint: 'Must match an account in the Accounts sheet or an existing account' },
    { key: 'stakeholderType', header: 'Stakeholder Type', headerAliases: ['Type'], type: 'enum', options: ['CLIENT', 'SERVICE_PROVIDER'], required: true, default: 'CLIENT', example: 'CLIENT' },
    { key: 'influence', header: 'Influence Level', headerAliases: ['Influence'], type: 'enum', options: INFLUENCE, required: true, example: 'High' },
    { key: 'relationship', header: 'Relationship', type: 'enum', options: RELATIONSHIP, required: true, example: 'Strong' },
    { key: 'designation', header: 'Designation', type: 'string', example: 'CTO' },
    { key: 'department', header: 'Department', type: 'string', example: 'Engineering' },
    { key: 'email', header: 'Email', type: 'string', format: 'email', example: 'jane@acme.com', hint: 'Unique within the account' },
    { key: 'phone', header: 'Phone', type: 'string', format: 'phone' },
    { key: 'linkedinProfileUrl', header: 'LinkedIn Profile URL', headerAliases: ['LinkedIn', 'LinkedIn Profile', 'LinkedIn URL'], type: 'string', format: 'website', example: 'https://linkedin.com/in/janedoe' },
  ],
  exportColumns: [
    { key: 'name', header: 'Name', value: (e) => e.name ?? '' },
    { key: 'accountId', header: 'Account', value: (e, ref) => e.accountName ?? accName(e.accountId, ref) },
    { key: 'stakeholderType', header: 'Stakeholder Type', value: (e) => e.stakeholderType ?? 'CLIENT' },
    { key: 'influence', header: 'Influence Level', value: (e) => e.influence ?? '' },
    { key: 'relationship', header: 'Relationship', value: (e) => e.relationship ?? '' },
    { key: 'designation', header: 'Designation', value: (e) => e.designation ?? '' },
    { key: 'department', header: 'Department', value: (e) => e.department ?? '' },
    { key: 'email', header: 'Email', value: (e) => e.email ?? '' },
    { key: 'phone', header: 'Phone', value: (e) => e.phone ?? '' },
    { key: 'linkedinProfileUrl', header: 'LinkedIn Profile URL', value: (e) => e.linkedinProfileUrl ?? '' },
  ],
};

// ─── Action Items ─────────────────────────────────────────────────────────────
const actionItemsConfig: ModuleIEConfig = {
  moduleKey: 'actionItems',
  label: 'Action Items',
  singular: 'Action Item',
  duplicateKeyLabel: 'Title + Account',
  fields: [
    { key: 'title', header: 'Task Title', headerAliases: ['Title', 'Task'], type: 'string', required: true, example: 'Follow up on proposal' },
    { key: 'accountId', header: 'Account', headerAliases: ['Account Name'], type: 'reference', reference: 'account', required: true, example: 'Acme Corporation', hint: 'Must match an account in the Accounts sheet or an existing account' },
    { key: 'ownerStakeholderId', header: 'Owner', headerAliases: ['Task Owner', 'Owner Stakeholder'], type: 'reference', reference: 'stakeholder', required: true, example: 'John Smith', hint: 'Must match a Client or Service Provider stakeholder on the same account (Stakeholders sheet or existing)' },
    { key: 'priority', header: 'Priority', type: 'enum', options: PRIORITY, required: true, example: 'High' },
    { key: 'status', header: 'Status', type: 'enum', options: ACTION_ITEM_STATUS_OPTIONS, required: true, example: 'To Do' },
    { key: 'actionItemType', header: 'Type', headerAliases: ['Action Item Type', 'Type of Action Item'], type: 'enum', options: ACTION_ITEM_TYPE_OPTIONS, example: 'Stakeholder connect' },
    { key: 'projectId', header: 'Project', headerAliases: ['Project Name'], type: 'reference', reference: 'project', hint: 'Optional; setting Project classifies this row as a Project Action Item' },
    { key: 'opportunityId', header: 'Opportunity', headerAliases: ['Opportunity Name'], type: 'reference', reference: 'opportunity', hint: 'Optional; must belong to the same account (Opportunities sheet or existing)' },
    { key: 'openDate', header: 'Open Date', type: 'date', example: '2026-01-10' },
    { key: 'dueDate', header: 'Due Date', type: 'date', example: '2026-02-10' },
    { key: 'notes', header: 'Description', headerAliases: ['Notes'], type: 'string' },
    { key: 'risksAndDependencies', header: 'Risks & Dependencies', type: 'string' },
    { key: 'completedDate', header: 'Completed Date', type: 'date' },
  ],
  exportColumns: [
    { key: 'title', header: 'Task Title', value: (e) => e.title ?? '' },
    { key: 'accountId', header: 'Account', value: (e, ref) => e.accountName ?? accName(e.accountId, ref) },
    { key: 'projectId', header: 'Project', value: (e) => e.projectName ?? e.project ?? '' },
    { key: 'owner', header: 'Owner', value: (e) => e.ownerName ?? e.owner ?? '' },
    { key: 'priority', header: 'Priority', value: (e) => e.priority ?? '' },
    { key: 'status', header: 'Status', value: (e) => e.status ?? '' },
    { key: 'actionItemType', header: 'Type', value: (e) => e.actionItemType ?? '' },
    { key: 'opportunityId', header: 'Opportunity', value: (e, ref) => (e.opportunityId ? oppName(e.opportunityId, ref) : '') },
    { key: 'openDate', header: 'Open Date', value: (e) => e.openDate ?? '' },
    { key: 'dueDate', header: 'Due Date', value: (e) => e.dueDate ?? '' },
    { key: 'notes', header: 'Description', value: (e) => e.notes ?? '' },
    { key: 'risksAndDependencies', header: 'Risks & Dependencies', value: (e) => e.risksAndDependencies ?? '' },
    { key: 'completedDate', header: 'Completed Date', value: (e) => e.completedDate ?? '' },
    { key: 'financialYear', header: 'Financial Year', value: (e) => e.financialYear ?? '' },
    { key: 'quarter', header: 'Quarter', value: (e) => e.quarter ?? '' },
  ],
};

export const IE_CONFIGS: Record<IEModuleKey, ModuleIEConfig> = {
  accounts: accountsConfig,
  opportunities: opportunitiesConfig,
  stakeholders: stakeholdersConfig,
  actionItems: actionItemsConfig,
};
